import { Button } from "@/components/ui/button"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Input } from "@/components/ui/input"
import { Badge } from "@/components/ui/badge"
import { Search, Star, Users, Gamepad2, Sparkles, Bot, BookOpen, Wand2 } from "lucide-react"
import Link from "next/link"
import Image from "next/image"

const featuredGames = [
  {
    id: "baldurs-gate-3",
    title: "Baldur's Gate 3",
    description: "An epic RPG adventure with deep storytelling and tactical combat",
    genre: ["RPG", "Strategy"],
    rating: 4.9,
    players: "1-4 Players",
    releaseDate: "2023",
    image: "/placeholder.svg?height=300&width=400",
    autoGenerated: true,
  },
  {
    id: "spider-man-2",
    title: "Marvel's Spider-Man 2",
    description: "Swing through New York as both Peter Parker and Miles Morales",
    genre: ["Action", "Adventure"],
    rating: 4.8,
    players: "Single Player",
    releaseDate: "2023",
    image: "/placeholder.svg?height=300&width=400",
    autoGenerated: true,
  },
  {
    id: "starfield",
    title: "Starfield",
    description: "Explore the vast cosmos in Bethesda's space exploration RPG",
    genre: ["RPG", "Sci-Fi"],
    rating: 4.6,
    players: "Single Player",
    releaseDate: "2023",
    image: "/placeholder.svg?height=300&width=400",
    autoGenerated: true,
  },
]

export default function HomePage() {
  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60 sticky top-0 z-50">
        <div className="container mx-auto px-4 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-2">
              <Gamepad2 className="h-8 w-8 text-primary" />
              <h1 className="text-2xl font-bold">GameVault AI</h1>
              <Badge variant="secondary" className="ml-2">
                <Bot className="h-3 w-3 mr-1" />
                AI-Powered
              </Badge>
            </div>
            <nav className="hidden md:flex items-center space-x-6">
              <Link href="/" className="text-foreground hover:text-primary transition-colors">
                Home
              </Link>
              <Link href="/games" className="text-muted-foreground hover:text-primary transition-colors">
                All Games
              </Link>
              <Link href="/name-generator" className="text-muted-foreground hover:text-primary transition-colors">
                Name Generator
              </Link>
              <Link href="/tutorials" className="text-muted-foreground hover:text-primary transition-colors">
                Tutorials
              </Link>
              <Link href="/admin" className="text-muted-foreground hover:text-primary transition-colors">
                Admin
              </Link>
            </nav>
          </div>
        </div>
      </header>

      {/* Hero Section */}
      <section className="py-20 px-4 bg-gradient-to-br from-primary/10 via-background to-secondary/10">
        <div className="container mx-auto text-center">
          <div className="flex items-center justify-center space-x-2 mb-4">
            <Sparkles className="h-8 w-8 text-primary" />
            <h2 className="text-5xl font-bold bg-gradient-to-r from-primary to-secondary bg-clip-text text-transparent">
              AI-Powered Game Discovery
            </h2>
          </div>
          <p className="text-xl text-muted-foreground mb-8 max-w-3xl mx-auto">
            Automatically discover the latest games, generate comprehensive reviews, create detailed tutorials, and even
            generate unique game names - all powered by AI
          </p>
          <div className="flex flex-col sm:flex-row gap-4 justify-center items-center max-w-md mx-auto mb-8">
            <div className="relative flex-1 w-full">
              <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-muted-foreground h-4 w-4" />
              <Input placeholder="Search for games..." className="pl-10 w-full" />
            </div>
            <Button size="lg" className="w-full sm:w-auto">
              <Bot className="h-4 w-4 mr-2" />
              AI Search
            </Button>
          </div>

          {/* Quick Actions */}
          <div className="grid grid-cols-1 md:grid-cols-3 gap-4 max-w-4xl mx-auto">
            <Link href="/name-generator">
              <Card className="hover:shadow-lg transition-shadow cursor-pointer">
                <CardContent className="p-6 text-center">
                  <Wand2 className="h-8 w-8 text-primary mx-auto mb-3" />
                  <h3 className="font-semibold mb-2">Game Name Generator</h3>
                  <p className="text-sm text-muted-foreground">Generate unique and creative game names with AI</p>
                </CardContent>
              </Card>
            </Link>
            <Link href="/auto-collect">
              <Card className="hover:shadow-lg transition-shadow cursor-pointer">
                <CardContent className="p-6 text-center">
                  <Bot className="h-8 w-8 text-primary mx-auto mb-3" />
                  <h3 className="font-semibold mb-2">Auto Game Collection</h3>
                  <p className="text-sm text-muted-foreground">Automatically collect latest game information</p>
                </CardContent>
              </Card>
            </Link>
            <Link href="/tutorials">
              <Card className="hover:shadow-lg transition-shadow cursor-pointer">
                <CardContent className="p-6 text-center">
                  <BookOpen className="h-8 w-8 text-primary mx-auto mb-3" />
                  <h3 className="font-semibold mb-2">AI Tutorials</h3>
                  <p className="text-sm text-muted-foreground">Generate detailed gameplay tutorials with images</p>
                </CardContent>
              </Card>
            </Link>
          </div>
        </div>
      </section>

      {/* Auto-Generated Content Notice */}
      <section className="py-8 px-4 bg-muted/30">
        <div className="container mx-auto">
          <div className="flex items-center justify-center space-x-2 mb-4">
            <Bot className="h-5 w-5 text-primary" />
            <span className="text-sm font-medium">Latest Auto-Generated Content</span>
          </div>
          <p className="text-center text-muted-foreground max-w-2xl mx-auto">
            Our AI system automatically collects game information from multiple sources, generates comprehensive
            reviews, creates detailed tutorials, and updates content daily to keep you informed about the latest games.
          </p>
        </div>
      </section>

      {/* Featured Games */}
      <section className="py-16 px-4">
        <div className="container mx-auto">
          <div className="flex items-center justify-between mb-8">
            <div>
              <h3 className="text-3xl font-bold mb-2">AI-Generated Game Reviews</h3>
              <p className="text-muted-foreground">Comprehensive reviews automatically generated and updated</p>
            </div>
            <div className="flex space-x-2">
              <Button variant="outline" size="sm">
                <Bot className="h-4 w-4 mr-2" />
                Refresh Content
              </Button>
              <Link href="/games">
                <Button variant="outline">View All Games</Button>
              </Link>
            </div>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
            {featuredGames.map((game) => (
              <Card key={game.id} className="overflow-hidden hover:shadow-lg transition-shadow group">
                <div className="relative overflow-hidden">
                  <Image
                    src={game.image || "/placeholder.svg"}
                    alt={game.title}
                    width={400}
                    height={300}
                    className="w-full h-48 object-cover group-hover:scale-105 transition-transform duration-300"
                  />
                  <div className="absolute top-4 right-4">
                    <Badge variant="secondary" className="bg-background/80 backdrop-blur">
                      {game.releaseDate}
                    </Badge>
                  </div>
                  {game.autoGenerated && (
                    <div className="absolute top-4 left-4">
                      <Badge className="bg-primary/80 backdrop-blur">
                        <Bot className="h-3 w-3 mr-1" />
                        AI Generated
                      </Badge>
                    </div>
                  )}
                </div>
                <CardHeader>
                  <div className="flex items-start justify-between">
                    <CardTitle className="text-xl">{game.title}</CardTitle>
                    <div className="flex items-center space-x-1">
                      <Star className="h-4 w-4 fill-yellow-400 text-yellow-400" />
                      <span className="text-sm font-medium">{game.rating}</span>
                    </div>
                  </div>
                  <CardDescription className="text-base">{game.description}</CardDescription>
                </CardHeader>
                <CardContent>
                  <div className="flex flex-wrap gap-2 mb-4">
                    {game.genre.map((g) => (
                      <Badge key={g} variant="outline">
                        {g}
                      </Badge>
                    ))}
                  </div>
                  <div className="flex items-center justify-between">
                    <div className="flex items-center space-x-1 text-sm text-muted-foreground">
                      <Users className="h-4 w-4" />
                      <span>{game.players}</span>
                    </div>
                    <div className="flex space-x-2">
                      <Link href={`/games/${game.id}`}>
                        <Button size="sm">View Details</Button>
                      </Link>
                      <Link href={`/tutorials/${game.id}`}>
                        <Button size="sm" variant="outline">
                          <BookOpen className="h-3 w-3 mr-1" />
                          Tutorial
                        </Button>
                      </Link>
                    </div>
                  </div>
                </CardContent>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-16 px-4 bg-muted/30">
        <div className="container mx-auto">
          <h3 className="text-3xl font-bold text-center mb-12">AI-Powered Features</h3>
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-6">
            <Card>
              <CardContent className="p-6 text-center">
                <Bot className="h-12 w-12 text-primary mx-auto mb-4" />
                <h4 className="font-semibold mb-2">Auto Game Collection</h4>
                <p className="text-sm text-muted-foreground">
                  Automatically scrapes and collects information about the latest 100 games from multiple sources
                </p>
              </CardContent>
            </Card>
            <Card>
              <CardContent className="p-6 text-center">
                <Sparkles className="h-12 w-12 text-primary mx-auto mb-4" />
                <h4 className="font-semibold mb-2">AI Content Generation</h4>
                <p className="text-sm text-muted-foreground">
                  Generates comprehensive game descriptions, features, and interesting highlights using AI
                </p>
              </CardContent>
            </Card>
            <Card>
              <CardContent className="p-6 text-center">
                <BookOpen className="h-12 w-12 text-primary mx-auto mb-4" />
                <h4 className="font-semibold mb-2">Interactive Tutorials</h4>
                <p className="text-sm text-muted-foreground">
                  Creates detailed, image-rich gameplay tutorials and guides automatically
                </p>
              </CardContent>
            </Card>
            <Card>
              <CardContent className="p-6 text-center">
                <Wand2 className="h-12 w-12 text-primary mx-auto mb-4" />
                <h4 className="font-semibold mb-2">Name Generator</h4>
                <p className="text-sm text-muted-foreground">
                  Generate unique and creative game names based on genre, theme, and style preferences
                </p>
              </CardContent>
            </Card>
          </div>
        </div>
      </section>

      {/* Stats Section */}
      <section className="py-16 px-4">
        <div className="container mx-auto">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-8 text-center">
            <div>
              <h4 className="text-4xl font-bold text-primary mb-2">100+</h4>
              <p className="text-muted-foreground">Auto-Collected Games</p>
            </div>
            <div>
              <h4 className="text-4xl font-bold text-primary mb-2">500+</h4>
              <p className="text-muted-foreground">AI-Generated Tutorials</p>
            </div>
            <div>
              <h4 className="text-4xl font-bold text-primary mb-2">1000+</h4>
              <p className="text-muted-foreground">Generated Game Names</p>
            </div>
            <div>
              <h4 className="text-4xl font-bold text-primary mb-2">24/7</h4>
              <p className="text-muted-foreground">Auto-Updates</p>
            </div>
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="bg-muted py-12 px-4">
        <div className="container mx-auto">
          <div className="grid grid-cols-1 md:grid-cols-4 gap-8">
            <div>
              <div className="flex items-center space-x-2 mb-4">
                <Gamepad2 className="h-6 w-6 text-primary" />
                <span className="text-lg font-bold">GameVault AI</span>
              </div>
              <p className="text-muted-foreground">
                The world's first AI-powered gaming discovery platform with automatic content generation.
              </p>
            </div>
            <div>
              <h5 className="font-semibold mb-4">AI Features</h5>
              <ul className="space-y-2 text-muted-foreground">
                <li>
                  <Link href="/auto-collect" className="hover:text-primary transition-colors">
                    Auto Game Collection
                  </Link>
                </li>
                <li>
                  <Link href="/name-generator" className="hover:text-primary transition-colors">
                    Name Generator
                  </Link>
                </li>
                <li>
                  <Link href="/tutorials" className="hover:text-primary transition-colors">
                    AI Tutorials
                  </Link>
                </li>
                <li>
                  <Link href="/content-generation" className="hover:text-primary transition-colors">
                    Content Generation
                  </Link>
                </li>
              </ul>
            </div>
            <div>
              <h5 className="font-semibold mb-4">Games</h5>
              <ul className="space-y-2 text-muted-foreground">
                <li>
                  <Link href="/games" className="hover:text-primary transition-colors">
                    All Games
                  </Link>
                </li>
                <li>
                  <Link href="/genres" className="hover:text-primary transition-colors">
                    By Genre
                  </Link>
                </li>
                <li>
                  <Link href="/latest" className="hover:text-primary transition-colors">
                    Latest Releases
                  </Link>
                </li>
                <li>
                  <Link href="/trending" className="hover:text-primary transition-colors">
                    Trending Games
                  </Link>
                </li>
              </ul>
            </div>
            <div>
              <h5 className="font-semibold mb-4">Tools</h5>
              <ul className="space-y-2 text-muted-foreground">
                <li>
                  <Link href="/admin" className="hover:text-primary transition-colors">
                    Admin Panel
                  </Link>
                </li>
                <li>
                  <Link href="/api-docs" className="hover:text-primary transition-colors">
                    API Documentation
                  </Link>
                </li>
                <li>
                  <Link href="/settings" className="hover:text-primary transition-colors">
                    Settings
                  </Link>
                </li>
                <li>
                  <Link href="/help" className="hover:text-primary transition-colors">
                    Help Center
                  </Link>
                </li>
              </ul>
            </div>
          </div>
          <div className="border-t mt-8 pt-8 text-center text-muted-foreground">
            <p>&copy; 2024 GameVault AI. Powered by artificial intelligence.</p>
          </div>
        </div>
      </footer>
    </div>
  )
}
